//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YapiMalzemeleriOdev.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public short urun_id { get; set; }
        public Nullable<short> kategori_id { get; set; }
        public string urun_ad { get; set; }
        public Nullable<short> urun_adet { get; set; }
        public Nullable<short> urun_fiyat { get; set; }
        public Nullable<short> garanti_suresi { get; set; }
        public string urun_guc { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
